//
//--------------------------------------------------------------------------------
//          THIS FILE WAS AUTOMATICALLY GENERATED BY THE GENESIS2 ENGINE        
//  FOR MORE INFORMATION: OFER SHACHAM (CHIP GENESIS INC / STANFORD VLSI GROUP)
//    Genesis2 is free software as governed by a BSD-style license,
//    see LICENSE.txt for specific terms and conditions.
//--------------------------------------------------------------------------------
//
//  
//	-----------------------------------------------
//	|            Genesis Release Info             |
//	|  $Change: 11907 $ --- $Date: 2025/06/23 $   |
//	-----------------------------------------------
//	
//
//  Source file: test/module_cache/src/child.svp
//  Source template: child
//
// --------------- Begin Pre-Generation Parameters Status Report ---------------
//
//	From 'generate' statement (priority=5):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Command Line input (priority=4):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From XML input (priority=3):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Config File input (priority=2):
//
// ---------------- End Pre-Generation Pramameters Status Report ----------------

// Child module

// out_val (_GENESIS2_DECLARATION_PRIORITY_) = 1
//

module child_unq1 (
    output logic [7:0] out
);

out = 8'd1;

endmodule : child_unq1
