//
//--------------------------------------------------------------------------------
//          THIS FILE WAS AUTOMATICALLY GENERATED BY THE GENESIS2 ENGINE        
//  FOR MORE INFORMATION: OFER SHACHAM (CHIP GENESIS INC / STANFORD VLSI GROUP)
//    Genesis2 is free software as governed by a BSD-style license,
//    see LICENSE.txt for specific terms and conditions.
//--------------------------------------------------------------------------------
//
//  
//	-----------------------------------------------
//	|            Genesis Release Info             |
//	|  $Change: 11905 $ --- $Date: 2025/05/06 $   |
//	-----------------------------------------------
//	
//
//  Source file: /nobackup/steveri/github/Genesis2/test/glctest/global_controller/rtl/genesis/flop.svp
//  Source template: flop
//
// --------------- Begin Pre-Generation Parameters Status Report ---------------
//
//	From 'generate' statement (priority=5):
// Parameter Default 	= 0
// Parameter Width 	= 32
// Parameter Type 	= REFlop
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Command Line input (priority=4):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From XML input (priority=3):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Config File input (priority=2):
//
// ---------------- End Pre-Generation Pramameters Status Report ----------------

/* *****************************************************************************
 * File: flop.vp
 * 
 * Description:
 * Genesis2 flip-flop generator.
 * 
 * Required Genesis2 Controlable Parameters:
 * * Type		- Constant, Flop, RFlop, EFlop, or REFlop
 * * Width		- integer value specifying register width
// From /nobackup/steveri/github/Genesis2/test/glctest/global_controller/rtl/genesis/flop.svp line 10
 * * Default		- default value for the flop 
 *			 (only applies when flop_type=constant|rflop|reflop)
 * * SyncMode		- Sync or ASync flop * Change bar:
 * 
 * 
 * -----------
 * Date          Author   Description
 * Mar 30, 2010  shacham  init version  --  
 * May 20, 2014  jingpu   Add Async mode, change to active low reset
 * Feb 20, 2018  ajcars   Change back to active high reset 
// From /nobackup/steveri/github/Genesis2/test/glctest/global_controller/rtl/genesis/flop.svp line 20
 * ****************************************************************************/


/*******************************************************************************
 * REQUIRED PARAMETERIZATION
 ******************************************************************************/
// Type (_GENESIS2_INHERITANCE_PRIORITY_) = REFlop
//
// Default (_GENESIS2_INHERITANCE_PRIORITY_) = 0
//
// Width (_GENESIS2_INHERITANCE_PRIORITY_) = 32
//
// SyncMode (_GENESIS2_DECLARATION_PRIORITY_) = ASync
//

module flop_D_0_T_REFlop_W_32(
	       //inputs
	       input 		   Clk,
	       input [31:0]  din,
	       input 		   Reset,
	       input 		   en,
// From /nobackup/steveri/github/Genesis2/test/glctest/global_controller/rtl/genesis/flop.svp line 50

	       //outputs
	       output reg [31:0] dout
	       );




   
   always_ff @(posedge Clk or posedge Reset) begin
      if (Reset) 
	dout <= 32'h0;
      else if (en)
// From /nobackup/steveri/github/Genesis2/test/glctest/global_controller/rtl/genesis/flop.svp line 80
	dout <= din;
   end

// From /nobackup/steveri/github/Genesis2/test/glctest/global_controller/rtl/genesis/flop.svp line 90
endmodule
