FROM docker.io/ubuntu:20.04
RUN apt-get update && \
    apt-get install -y \
    python3 python3-dev python3-pip python3-venv

RUN mkdir -p /aha && cd /aha && python -m venv . && source bin/activate && \
  pip install genesis2
