FROM docker.io/ubuntu:20.04
RUN apt-get update && \
    apt-get install -y \
    git python3 python3-venv && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3 100 && \
    update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 100 && \
    echo DONE

# Switch shell to bash
SHELL ["/bin/bash", "--login", "-c"]

RUN \
  mkdir -p /aha && cd /aha && python -m venv . && source bin/activate && \
  python3 -m pip install genesis2
