# % (cd /nobackup/steveri/github; less */.github/workflows/*.yml)


name: Gold Compare

# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master

# Runs on every push. Note (I think) PR triggers at least one push?
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Action, branch, and repo information.
      # run: echo Action = ${{ github.event_name }}, branch = ${{ github.ref }}
      run: printf "\n\n    Action = ${{ github.event_name }}, branch = ${{ github.ref }}\n\n"
      #  echo "Branch '${{ github.ref }}' in repo '${{ github.repository }}'."

    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Gold Test
      run: |
        printf '\n\n\n    GOLD TEST\n\n\n'
        test/genesis-ci.sh master ${{ github.ref }}
        printf '\n\n\n'
