name: Pip Install

on:
  push:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Pip install genesis2 from docker
        run: |
          pwd; ls -l
          docker build --file Dockerfile.genesis .

  pip-install:
    runs-on: ubuntu-latest
    name: Check 'pip install genesis2'

    steps:
      - name: Pip install genesis2
        run: |
            pwd


#           python -m venv .
#           source bin/activate
#           pip list -v
#           pip install genesis2
